apiVersion: accelerator.tanzu.vmware.com/v2
kind: Accelerator
metadata:
  name: simple-accelerator
spec:
  displayName: Simple Accelerator
  description: Contains just a README
  iconURL: https://images.freecreatives.com/wp-content/uploads/2015/05/smiley-559124_640.jpg
  tags:
    - simple
    - getting-started
  git:
    ref:
      branch: main
    url: https://github.com/trisberg/simple-accelerator
